version: '3.9'

services:
  api:
    container_name: duet-api
    env_file:
      - .env
    build:
      context: ../.
      dockerfile: ./docker/containers/api/Dockerfile
    ports:
      - ${API_PORT:-4000}:${API_PORT:-4000}
    restart: always

volumes:
  postgres:
    name: duet-backend
