name: Deploy by runner

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Open devOps directory
        run: cd ~/devops/
      - name: TEST
        run: pwd
      - name: Update server directory from git
        run: git submodule update --reference server --remote
      - name: Build and up container
        run: ./build.sh rebuild server
      - name: Clean old images
        run: ./build.sh clean
