name: Deploy by runner

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Update server directory from git
        run: |
          cd ~/devops/
          git submodule update --reference server --remote
      - name: Build and up container
        run: ~/devops/build.sh rebuild server
      - name: Clean old images
        run: ~/devops/build.sh clean
