name: Deploy by runner

on:
  push:
    branches:
      - master

jobs:
  pull:
    runs-on: self-hosted
    steps:
      - name: Pull data from GitHub repository
        run: |
          cd ~/app
          git submodule update --reference server --remote
  build:
    runs-on: self-hosted
    needs: pull
    steps:
      - name: Run local rebuild container script
        run: |
          cd ~/app
          ./build.sh rebuild server
  clean:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Clean old images
        run: |
          cd ~/app
          ./build.sh clean

