name: Deploy by runner

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Update server directory from git
        run: |
          cd ~/
          git submodule update --reference server --remote
      - name: TEST
        run: |
          pwd
#      - name: Build and up container
#        run: |
#          cd ~/devops/
#          ./build.sh rebuild server
#      - name: Clean old images
#        run: |
#          cd ~/devops/
#          ./build.sh clean
